# Page settings
baseurl = "/"
title = "Ultranet Communication Nepal"
keywords = "internet service provider in Karve"
languageCode = "en-us"
theme = "hugo-elate-theme"
logo = "logo.png"

#[permalinks]
#  post = "/:year/:month/:title/"

[params]

  custom_css = [ "css/modified-custom1.css", "css/modified-custom2.css" ]
  googleMapsApiKey = "AIzaSyAEOcPGx2ufv6fIOMt8pylCw3IjVCoveBw"
  khalti_test_pubkey = "test_public_key_fd5ba42ac3644076a3f805a63b99e536"
  khalti_test_pubsec = "test_secret_key_966a63c419aa43c9a2faecc8fd436ce1"

  # Meta
  author = "Ultranet"
  description = "Reliable and affordable internet service provider in Karve district, offering high quality internet to speed up browsing experience and increase business productivities."
  email = "info@ultranet.com.np"

  # Navigation
  [params.navigation]
    brand = "Ultranet"
    home = "Home"
    work = "Fiber TV"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # Add custom links before or after the default links
    # Assign a weight to define the order

  #prepended links
#  [[menu.prepend]]
#    url = ""
#    name = ""
#    weight = 10

  # postpended links
#  [[menu.postpend]]
#    url = "http://ultranet.com.np/store/"
#    name = "Shop"
#    weight = 10

  #  url = ""
  #  name = "Sign Up"
  #  weight = 20

  # Hero section
  [params.hero]
    subtitle = "immerse in Fast Internet experience"
    title = "Ultranet"

  # Intro section
  # Available icons: https://pagellapolitica.it/static/plugins/line-icons
  [params.intro]

  [[params.intro.item]]
    title = "11Mbps"
    description = "Rs 3450 for 3 months"
    url = "http://www.ultranet.com.np/shop/online-exclusive/"
    target = "_blank"
    button = "Online Exclusive"
    icon = "icon-magic-wand"
    img = "online-exclusive.jpg"

  [[params.intro.item]]
    title = "6Mbps + IPTV"
    description = "Rs 600/month for 12 months"
    url = "http:/www.ultranet.com.np/shop/fibre-for-student/"
    target = "_blank"
    button = "Fibre for Student"
    icon = "icon-eyeglass"
    img = "student-fibre.jpg"

  [[params.intro.item]]
    title = "11Mbps + IPTV"
    description = "Rs 900/month for 12 months"
    url = "http://www.ultranet.com.np/shop/fibre-for-home/"
    target = "_blank"
    button = "Fibre for Home"
    icon = "icon-home"
    img = "home-fibre.jpg"
    identity = "11mbps"

  [[params.intro.item]]
    title = "22Mbps + IPTV"
    description = "1"
    url = "http://www.ultranet.com.np/shop/fibre-for-startups/"
    target = "_blank"
    button = "Fibre for Startup"
    icon = "icon-bulb"
    img = "startup-fibre.jpg"
    identity = "22mbps"

  [[params.intro.item]]
    title = "33Mbps + IPTV"
    description = "Rs 1300/month for 12 months"
    url = "http://www.ultranet.com.np/shop/fibre-for-cafe/"
    target = "_blank"
    button = "Fibre for Cafe"
    icon = "icon-cup"
    img = "cafe-fibre.jpg"
    identity = "33mbps"

  [[params.intro.item]]
    title = "44Mbps + IPTV"
    description = "Rs 1500/month for 12 months"
    url = "http://www.ultranet.com.np/shop/fibre-for-business/"
    target = "_blank"
    button = "Fibre for Business"
    icon = "icon-briefcase"
    img = "business-fibre.jpg"
    identity = "44mbps"

# Intro Item Templates
#  [[params.intro.item]]
#    title = ""
#    description = ""
#    url = "#"
#    button = ""
#    icon = ""
#    img = ""

  [params.intro.video]
    enable = true
    title = "Turbo Up, Nepal!"
    icon = "icon-control-play"
    url = "https://vimeo.com/296158462"
    #url = "https://www.facebook.com/ultranetcommunication/videos/351474302064649/"


  # Work section
  [params.work]
    enable = true
    title = "The Non-stop Experience"
    description = "Get great Entertainment from the world popular TV channels and watch 'em all in High Definition"
    footertext = ""

  [[params.work.row]]
    img = "axn.jpg"
    alt = "Fear Factor Poster"
    title = "AXN Channel"
    subtitle = ""

#  [[params.work.row]]
#    img = "zing.jpg"
#    alt = "Billo Poster"
#    title = "Zing Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "cartoonnetwork.jpg"
#    alt = "Pokemon Poster"
#    title = "Cartoon Network Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "hbo.jpg"
#    alt = "The Game of Thrones Poster"
#    title = "HBO Channel"
#    subtitle = ""

  [[params.work.row]]
    img = "natgeo.jpg"
    alt = "Life Below Zero Paster"
    title = "National Geographic Channel"
    subtitle = ""

  [[params.work.row]]
    img = "sonyespn.jpg"
    alt = "Sunday NFL Countdown Poster"
    title = "Sony ESPN Channel"
    subtitle = ""

  [[params.work.row]]
    img = "cnn.jpg"
    alt = "CNN Heroes Poster"
    title = "CNN Channel"
    subtitle = ""

  [[params.work.row]]
    img = "zoom.jpg"
    alt = "Kabali Poster"
    title = "Zoom Channel"
    subtitle = ""

  [[params.work.row]]
    img = "mtv.jpg"
    alt = "Teen Wolf Poster"
    title = "MTV Music Channel"
    subtitle = ""

#  [[params.work.row]]
#    img = "sonymax.jpg"
#    alt = "American Next Top Model Poster"
#    title = "Sony Max Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "cctv.jpg"
#    alt = "Emperor in the Palace Poster"
#    title = "CCTV Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "tlc.jpg"
#    alt = "The Voice America Poster"
#    title = "Channel V"
#    subtitle = ""

#  [[params.work.row]]
#    img = "starworld.jpg"
#    alt = "Sherlock Poster"
#    title = "BBC Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "disneychannel.jpg"
#    alt = "Lilo and Sticth Poster"
#    title = "Disney Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "fox.jpg"
#    alt = "Once Upon A Time Poster"
#    title = "Starworld Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "diva.jpg"
#    alt = "Queen of South Poster"
#    title = "Fox Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "abc.jpg"
#    alt = "What Would You Do Poster"
#    title = "FX Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "animal-planet.jpg"
#    alt = "Too Cute Poster"
#    title = "Animal Planet Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "hbofamily.jpg"
#    alt = "Laws and Orders Special Victim Unit Poster"
#    title = "HBO Family Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "warnertv.jpg"
#    alt = "The Good Place Poster"
#    title = "Warner TV Channel"
#    subtitle = ""

#  [[params.work.row]]
#    img = "discovery.jpg"
#    alt = "Sherpa Poster"
#    title = "Discovery Channel"
#    subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = ""

    [[params.testimonials.item]]
      quote = "Just had installation earlier this morning. The guy was very professional and the connection was active as soon as he'd finished. Currently experiencing download speeds even quicker than is advertised! Great experience so far."
      person = 'Session <span class="subtext">Aasha Tamrakar Homestay</span>'
      img = "person1.jpg"
      alt = "Session Tamrakar"

    [[params.testimonials.item]]
      quote = "Best broadband installation I have ever had, so easy no waiting around Subesh was on time, worked quickly and when i had a small problem later on that evening he helped me to sort it straight away! Didn't even have to ring customer services and wait on hold for ages :) Thanks very much Subesh, great customer service!"
      person = 'Priyanka <span class="subtext">University of Kathmandu</span>'
      img = "person2.jpg"
      alt = "Priyanka"

    [[params.testimonials.item]]
      quote = "After some time trying to get my phone line working I received a call from Situ and in no time at all the issue was identified and resolved. Situ was brilliant, he clearly has a wealth of experience trouble shooting. Thank you Situ and Ultranet"
      person = 'Raj <span class="subtext">Hotel Manager</span>'
      img = "person3.jpg"
      alt = "Raj"


  # Services section
  [params.services]
    enable = true
    title = "The Future is Fibre"
    description = "Forget copper! As broadband demands increase with technological advancements, fibre optics are the new standard for higher network speeds, stability and quality."

    [[params.services.item]]
      title = "Full HD Enjoyment"
      description = "On fibre broadband, it takes only minutes for a full HD movie to finish downloading, and the increased rate means you can even stream shows to watch while they download. No more having to suffer the buffer!"
      icon = "icon-screen-desktop"

    [[params.services.item]]
      title = "Turbo Internet Speed"
      description = "Light travels faster, no questions about that. Since optic fibres transmit light, they can deliver much higher speeds than copper cables. A 100% fibre optic connection allows us to ensure that you get the speeds you subscribe to."
      icon = "icon-speedometer"

    [[params.services.item]]
      title = "Seamless Internet Calls"
      description = "Fibre broadband has the capacity to handle heavier demand on your bandwidth, so video calls on a fibre connection are clearer and more seamless. You might as well be talking to the person through a window!"
      icon = "icon-earphones-alt"

    [[params.services.item]]
      title = "Smooth Online Gaming"
      description = "Connection speed, denoted in megabits per second (Mbps), has become critical in order to be an accomplished player. With fibre broadband speeds currently in the hundreds and still climbing, users can enjoy minimal lag and a smooth connection – every gamer’s dream."
      icon = "icon-game-controller"

    [[params.services.item]]
      title = "Better Stability"
      description = "Fibre optics is much less susceptible to environmental factors such as temperature and electromagnetic interference. In addition, attenuation is lower with fibre optics as well. This translates to a more stable connection for you."
      icon = "icon-energy"

      [[params.services.item]]
      title = "Security Performance"
      description = "Fibre optic cables transmit data via light, they are much less susceptible to outside interference (no more network issues during rainy days) and much more reliable. You can shop to your heart’s content and not worry about your money disappearing into the black holes of the Internet."
      icon = "icon-shield"


  # About section
  [params.about]
    enable = true
    title = "Our Team"
    description = "Ultranet management team believes in Future-proof technology so we chose to implement the 100% fibre optics cables from end to end, unlike service providers who use a combination of copper and fibre optics. On top of that, we know our network infrastructure well to ensure the quality of the service we deliver to you."

    [[params.about.item]]
      name = "Subesh Tamrakar"
      position = "Managing Director"
      description = "The impetus to start a business comes in many forms; for Subesh Tamrakar, co-founder of Ultranet Communication, it was an abrupt firing that sparked the fire on his previos employer overseas. Later, He was convinced by family and college friends to open a internet service center; His wife arranged the financing and the rest is history. Today, Ultranet has nearly full coverage hotspots and boosts their internet subsribers to 23000 in the Kavre district."
      img = "subesh.jpg"
      alt = "Managing Director of Ultranet Communication"
      social = [
        ["icon-twitter", "https://www.twitter.com/sutamra/"],
        ["icon-facebook", "https://www.facebook.com/sutamra/"],
        ["icon-instagram", "https://www.instagram.com/sutamra/"]
      ]

    [[params.about.item]]
      name = "Situ Sainju"
      position = "ISP Civil Engineer"
      description = "An environmental and civil engineer, Situ Sainju, was the one who demostrates and engineeiring submarine cable network infrastructure in the company. That turned into the end result: Ultranet was launched and live. Though Subesh and Situ faced skepticism in the early days they forged ahead, creating a huge demanding internet industry in the region that’s still alive and kicking."
      img = "situ.jpg"
      alt = "Head of ISP Enginner of Ultranet Communication"
      social = [
        ["icon-twitter", "https://www.twitter.com/situ.sainju"],
        ["icon-facebook", "https://www.facebook.com/situ.sainju"],
        ["icon-instagram", "https://www.instagram.com/situ.sainju"]
      ]

    [[params.about.item]]
      name = "Sumita Shrestha"
      position = "Network & Server Engineer "
      description = " As a Network & Server engineer, Sumita's job is to sees the network as a large collection of discrete, separate functional elements that each have a function that contributes to the operational whole; then focussed on the Operating Systems and the platforms that run on them. Each system is discrete, and her tasks then transform to the convenient of the uninterrupted and fast internet service our users are enjoying."
      img = "sumita.jpg"
      alt = "Network and Server Engineer of Ultranet Communication"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-instagram", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Why Choose Us?"
    background = "counter_background.jpg"

    [[params.counters.item]]
      description = "Downloading K/b"
      icon = "icon-cloud-download"
      from = 0
      to = 66000
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "Uploading K/b"
      icon = "icon-cloud-upload"
      from = 0
      to = 33000
      interval = 40
      speed = 3000

    [[params.counters.item]]
      description = "Users"
      icon = "icon-users"
      from = 0
      to = 23000
      interval = 30
      speed = 3000

    [[params.counters.item]]
      description = "Coverages sq"
      icon = "icon-target"
      from = 0
      to = 130
      interval = 10
      speed = 3000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in Touch"
    description = "We're ready to help you! Leave your contact details and we will call you back within 24 hours."

    details = [
        ["icon-compass", 'Panauti Road, Banepa, Kavrepalanchok, Nepal'],
        ["icon-phone", '<a href="callto:00977011662729">+977011662729</a>'],
        ["icon-bubble", '<a href="http://wa.me/9779801116704">+9779801116704</a>'],
        ["icon-envelope", '<a href="mailto:info@ultranet.com.np">info@ultranet.com.np</a>'],
        ["icon-globe", "https://ultranet.com.np"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; 2018 Ultranet Communication Nepal. All Rights Reserved.'
    links = [
        ["icon-social-facebook", "https://facebook.com/ultranetcommunication"],
        ["icon-social-twitter", "https://twitter.com/ultranetcommunication"],
        ["icon-social-instagram", "https://instagram.com/ultranetcommunication"],
        ["icon-social-youtube", "https://youtube.com/user/ultranetcommunication"]
      ]
